-- ========== SHOWTIMES (bo sung phim chua co suat) ==========
-- Generated by scripts/generate_showtimes_seed.py
-- 32 suat

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1333, m.movie_id, 16, '2026-05-20 16:00:00', '2026-05-20 18:00:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 467905 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1334, m.movie_id, 24, '2026-05-20 16:00:00', '2026-05-20 17:57:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1542261 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1335, m.movie_id, 25, '2026-05-20 16:00:00', '2026-05-20 18:20:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1116201 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1336, m.movie_id, 17, '2026-05-20 16:00:00', '2026-05-20 18:40:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1319522 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1337, m.movie_id, 1, '2026-05-20 16:00:00', '2026-05-20 17:47:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1146058 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1338, m.movie_id, 30, '2026-05-20 16:00:00', '2026-05-20 17:53:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 608067 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1339, m.movie_id, 36, '2026-05-20 16:00:00', '2026-05-20 18:15:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1264821 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1340, m.movie_id, 26, '2026-05-20 16:00:00', '2026-05-20 18:15:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1667685 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1341, m.movie_id, 27, '2026-05-20 16:00:00', '2026-05-20 18:17:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1641479 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1342, m.movie_id, 31, '2026-05-20 16:00:00', '2026-05-20 18:15:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1512207 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1343, m.movie_id, 23, '2026-05-20 16:00:00', '2026-05-20 17:55:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1671608 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1344, m.movie_id, 10, '2026-05-20 16:00:00', '2026-05-20 18:13:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1697695 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1345, m.movie_id, 22, '2026-05-20 16:00:00', '2026-05-20 17:51:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1318447 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1346, m.movie_id, 28, '2026-05-20 16:00:00', '2026-05-20 18:23:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1630423 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1347, m.movie_id, 12, '2026-05-20 16:00:00', '2026-05-20 18:03:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1339713 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1348, m.movie_id, 11, '2026-05-20 16:00:00', '2026-05-20 18:03:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1266127 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1349, m.movie_id, 4, '2026-05-20 16:00:00', '2026-05-20 18:09:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1330021 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1350, m.movie_id, 2, '2026-05-20 16:00:00', '2026-05-20 18:37:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1419406 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1351, m.movie_id, 6, '2026-05-20 16:00:00', '2026-05-20 17:52:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 855435 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1352, m.movie_id, 13, '2026-05-20 16:00:00', '2026-05-20 17:49:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1292695 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1353, m.movie_id, 14, '2026-05-20 16:00:00', '2026-05-20 17:54:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1414413 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1354, m.movie_id, 29, '2026-05-20 16:00:00', '2026-05-20 17:53:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1122573 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1355, m.movie_id, 8, '2026-05-20 16:00:00', '2026-05-20 17:30:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1510745 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1356, m.movie_id, 5, '2026-05-20 16:00:00', '2026-05-20 17:53:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1684226 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1357, m.movie_id, 33, '2026-05-20 16:00:00', '2026-05-20 20:04:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1582770 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1358, m.movie_id, 18, '2026-05-20 16:00:00', '2026-05-20 18:04:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1628367 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1359, m.movie_id, 9, '2026-05-20 16:00:00', '2026-05-20 17:59:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1084577 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1360, m.movie_id, 19, '2026-05-20 16:00:00', '2026-05-20 18:26:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 361743 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1361, m.movie_id, 15, '2026-05-20 16:00:00', '2026-05-20 18:08:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 425274 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1362, m.movie_id, 3, '2026-05-20 16:00:00', '2026-05-20 18:00:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1325734 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1363, m.movie_id, 34, '2026-05-20 16:00:00', '2026-05-20 17:50:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 1254594 LIMIT 1;

INSERT IGNORE INTO showtimes (showtime_id, movie_id, room_id, start_time, end_time, base_price, status)
SELECT 1364, m.movie_id, 20, '2026-05-20 16:00:00', '2026-05-20 17:45:00', 90000.00, 'ACTIVE'
FROM movies m WHERE m.tmdb_id = 808 LIMIT 1;

-- ========== SHOWTIME_SEATS (AVAILABLE — tu bang seats theo room) ==========
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1333, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 16;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1334, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 24;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1335, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 25;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1336, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 17;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1337, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 1;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1338, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 30;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1339, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 36;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1340, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 26;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1341, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 27;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1342, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 31;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1343, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 23;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1344, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 10;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1345, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 22;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1346, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 28;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1347, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 12;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1348, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 11;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1349, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 4;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1350, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 2;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1351, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 6;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1352, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 13;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1353, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 14;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1354, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 29;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1355, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 8;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1356, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 5;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1357, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 33;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1358, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 18;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1359, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 9;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1360, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 19;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1361, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 15;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1362, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 3;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1363, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 34;
INSERT IGNORE INTO showtime_seats (showtime_id, seat_id, status, locked_by_user, locked_until)
SELECT 1364, s.seat_id, 'AVAILABLE', NULL, NULL FROM seats s WHERE s.room_id = 20;
