#!/usr/bin/env python3
"""Generate movies INSERT SQL from database/movies.json (TMDB-first schema)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOVIES_JSON = ROOT / "src/main/resources/database/movies.json"
OUT = ROOT / "src/main/resources/db/seed-movies-from-json.sql"

# phim id -> TMDB id (cong khai, phim chieu rap VN 2024-2025)
PHIM_TO_TMDB = {
    "phim001": 1223601,   # A Minecraft Movie
    "phim002": 823464,    # Godzilla x Kong
    "phim003": 1011985,   # Tham tu kien ky an khong dau (approx)
    "phim004": 1019404,   # Lat mat 8
    "phim005": 786892,    # Furiosa / action placeholder
    "phim006": 693134,    # Dune Part Two
    "phim007": 569094,    # Spider-Verse
    "phim008": 872585,    # Oppenheimer
    "phim009": 346698,    # Barbie
    "phim010": 447365,    # Guardians 3
}


def sql_escape(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def normalize_rating(r):
    if not r:
        return "P"
    r = str(r).strip().upper()
    if r in {"K", "P", "T13", "T16", "T18", "C18"}:
        return r
    return "P"


def tmdb_for(movie: dict, index: int) -> int:
    mid = movie.get("id", "")
    if mid in PHIM_TO_TMDB:
        return PHIM_TO_TMDB[mid]
    m = re.match(r"phim(\d+)", mid or "")
    if m:
        return 9700000 + int(m.group(1))
    return 9700000 + index


def main():
    movies = json.loads(MOVIES_JSON.read_text(encoding="utf-8"))
    lines = [
        "-- ========== MOVIES (from database/movies.json) ==========",
        "-- Generated by scripts/generate_movies_seed.py",
        "-- Can trung tmdb_id voi CinemaDemoSeedRunner / phim da import TMDB",
    ]
    count = 0
    for i, m in enumerate(movies, start=1):
        tmdb_id = tmdb_for(m, i)
        duration = m.get("duration") or 120
        age = normalize_rating(m.get("rating"))
        note = (m.get("id") or "") + ": " + (m.get("title") or "")[:200]
        lines.append(
            "INSERT IGNORE INTO movies "
            "(tmdb_id, duration, age_label, status, published_at, default_base_price, admin_note) VALUES ("
            f"{tmdb_id}, {int(duration)}, {sql_escape(age)}, 'ACTIVE', NOW(), 85000.00, {sql_escape(note)});"
        )
        count += 1
    lines.append(f"-- ({count} rows)")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {count} movie inserts to {OUT}")


if __name__ == "__main__":
    main()
