#!/usr/bin/env python3
"""Generate content_articles INSERT SQL from database/*.json for seed.sql."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB_DIR = ROOT / "src/main/resources/database"
OUT = ROOT / "src/main/resources/db/seed-content-articles.sql"

FILES = [
    ("PROMOTION", "promotion.json"),
    ("NEWS", "event.json"),
    ("FESTIVAL", "festival.json"),
]


def sql_escape(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def parse_date(d: str | None) -> str:
    if not d or not str(d).strip():
        return "NULL"
    parts = str(d).strip().split("-")
    if len(parts) == 3:
        y, m, day = parts[0], parts[1].zfill(2), parts[2].zfill(2)
        return f"'{y}-{m}-{day}'"
    return "NULL"


def load_articles(path: Path) -> list:
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and "event" in data:
        return data["event"]
    return []


def main():
    lines = [
        "-- ========== CONTENT_ARTICLES (from database/*.json) ==========",
        "-- Generated by scripts/generate_content_seed.py",
    ]
    total = 0
    for category, filename in FILES:
        path = DB_DIR / filename
        if not path.exists():
            continue
        articles = load_articles(path)
        lines.append(f"-- {category}: {len(articles)} bai")
        for a in articles:
            aid = a.get("id")
            if not aid:
                continue
            images_json = json.dumps(a.get("images") or [], ensure_ascii=False)
            lines.append(
                "INSERT IGNORE INTO content_articles "
                "(id, category, title, published_date, thumbnail, images, content_html, created_at, updated_at) VALUES ("
                f"{sql_escape(aid)}, {sql_escape(category)}, {sql_escape(a.get('title'))}, "
                f"{parse_date(a.get('date'))}, {sql_escape(a.get('thumbnail'))}, "
                f"{sql_escape(images_json)}, {sql_escape(a.get('contentHtml'))}, "
                "NOW(), NOW());"
            )
            total += 1
    lines.append(f"-- ({total} rows)")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {total} inserts to {OUT}")


if __name__ == "__main__":
    main()
