#!/usr/bin/env python3
"""Append extra users from database/user.json into seed SQL (LOCAL auth, password 123456)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
USER_JSON = ROOT / "src/main/resources/database/user.json"
OUT = ROOT / "src/main/resources/db/seed-users-from-json.sql"

BCRYPT_123456 = "$2a$12$Kry5fB4yN8Doz3xshxS7Y.Z0Qf8qAqyG7OepV.e98C.h9h8vjTj6O"
ROLE_MAP = {"admin": 1, "staff": 2, "customer": 3, "user": 3}


def sql_escape(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def slug_username(name: str, uid: str, used: set) -> str:
    base = re.sub(r"[^a-z0-9]+", "_", (name or uid).lower()).strip("_")[:40] or uid.lower()
    candidate = base
    n = 1
    while candidate in used:
        candidate = f"{base}_{n}"
        n += 1
    used.add(candidate)
    return candidate


def main():
    users = json.loads(USER_JSON.read_text(encoding="utf-8"))
    lines = [
        "-- ========== USERS (from database/user.json, bo sung) ==========",
        "-- Generated by scripts/generate_users_seed.py — mat khau: 123456",
    ]
    used_names = set()
    user_id = 100
    profile_id = 100
    count = 0
    for u in users:
        role_name = (u.get("role") or "customer").lower()
        role_id = ROLE_MAP.get(role_name, 3)
        email = (u.get("email") or "").strip().lower()
        if not email:
            continue
        username = slug_username(u.get("name", ""), u.get("id", "u"), used_names)
        full_name = (u.get("name") or username)[:100]
        phone = (u.get("phone") or "")[:20] or None
        lines.append(
            "INSERT IGNORE INTO users (user_id, username, password_hash, email, role_id, auth_provider, provider_id, created_at) VALUES ("
            f"{user_id}, {sql_escape(username)}, {sql_escape(BCRYPT_123456)}, {sql_escape(email)}, {role_id}, 'LOCAL', NULL, NOW());"
        )
        lines.append(
            "INSERT IGNORE INTO user_profiles (profile_id, user_id, full_name, phone_number, updated_at) VALUES ("
            f"{profile_id}, {user_id}, {sql_escape(full_name)}, {sql_escape(phone)}, NOW());"
        )
        user_id += 1
        profile_id += 1
        count += 1
    lines.append(f"-- ({count} users)")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {count} users to {OUT}")


if __name__ == "__main__":
    main()
