#!/usr/bin/env python3
"""
Lay 60 phim /movie/now_playing (vi-VN), goi /movie/{id} lay runtime,
suy age_label tu title (giong MovieAgeUtil), sinh seed SQL + JSON console.

Chay:
  python scripts/generate_movies_now_playing_seed.py

Can TMDB API key (application-local.properties hoac TMDB_API_KEY).
"""
from __future__ import annotations

import gzip
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCAL_PROPS = ROOT / "src/main/resources/application-local.properties"
OUT_SQL = ROOT / "src/main/resources/db/seed-movies-now-playing-60.sql"
OUT_JSON = ROOT / "src/main/resources/db/movies-now-playing-60.json"
TARGET = 60
LANG = "vi-VN"
DEFAULT_RUNTIME = 120
DEFAULT_PRICE = 85000.00

AGE_TAG = re.compile(
    r"(?:^|[^0-9])T(\d{1,2})(?:[^0-9]|$)|\b(K|P)\b",
    re.IGNORECASE,
)


def load_api_key() -> str:
    key = os.environ.get("TMDB_API_KEY") or os.environ.get("VITE_TMDB_V3_KEY")
    if key:
        return key.strip()
    if LOCAL_PROPS.exists():
        text = LOCAL_PROPS.read_text(encoding="utf-8")
        m = re.search(r"^tmdb\.api-key\s*=\s*(.+)$", text, re.MULTILINE)
        if m and m.group(1).strip() and "YOUR_" not in m.group(1):
            return m.group(1).strip()
    raise SystemExit("Chua co TMDB API key.")


def tmdb_get(api_key: str, path: str, params: dict | None = None) -> dict:
    q = {"api_key": api_key, "language": LANG}
    if params:
        q.update(params)
    url = "https://api.themoviedb.org/3" + path + "?" + urllib.parse.urlencode(q)
    req = urllib.request.Request(
        url,
        headers={"Accept": "application/json", "Accept-Encoding": "identity"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        raw = resp.read()
        if raw[:2] == b"\x1f\x8b":
            raw = gzip.decompress(raw)
        return json.loads(raw.decode("utf-8"))


def extract_age_label(title: str | None) -> str:
    if not title:
        return "P"
    m = AGE_TAG.search(title)
    if not m:
        return "P"
    if m.group(2):
        return m.group(2).upper()
    return f"T{m.group(1)}"


def sql_escape(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def collect_now_playing(api_key: str) -> list[dict]:
    """Gop now_playing (VN + global) va trending/week neu chua du 60."""
    seen: set[int] = set()
    items: list[dict] = []

    def add_from(path: str, extra: dict, max_pages: int = 8) -> None:
        page = 1
        while len(items) < TARGET and page <= max_pages:
            data = tmdb_get(api_key, path, {"page": str(page), **extra})
            for row in data.get("results") or []:
                tid = row.get("id")
                if tid and tid not in seen:
                    seen.add(tid)
                    items.append(row)
                    if len(items) >= TARGET:
                        return
            page += 1
            time.sleep(0.1)

    add_from("/movie/now_playing", {"region": "VN"})
    add_from("/movie/now_playing", {})
    add_from("/trending/movie/week", {})
    return items[:TARGET]


def enrich_movie(api_key: str, summary: dict) -> dict:
    tid = summary["id"]
    detail = tmdb_get(api_key, f"/movie/{tid}")
    title = detail.get("title") or detail.get("original_title") or ""
    runtime = detail.get("runtime")
    if runtime is None or runtime <= 0:
        runtime = DEFAULT_RUNTIME
    age = extract_age_label(title)
    return {
        "tmdb_id": tid,
        "title": title,
        "original_title": detail.get("original_title"),
        "runtime": runtime,
        "age_label": age,
        "release_date": detail.get("release_date"),
        "vote_average": detail.get("vote_average"),
    }


def main() -> None:
    api_key = load_api_key()
    summaries = collect_now_playing(api_key)
    if not summaries:
        raise SystemExit("Khong lay duoc now_playing tu TMDB.")

    enriched: list[dict] = []
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    print(f"=== TMDB catalog — dang lay chi tiet {len(summaries)} phim ===\n")
    for i, s in enumerate(summaries, 1):
        row = enrich_movie(api_key, s)
        enriched.append(row)
        title = (row["title"] or "")[:60]
        print(
            f"{i:2}. tmdb_id={row['tmdb_id']:>8}  runtime={row['runtime']:>3}m  "
            f"age={row['age_label']:<4}  {title}"
        )
        time.sleep(0.1)

    OUT_JSON.write_text(
        json.dumps(enriched, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    lines = [
        "-- ========== MOVIES: 60 phim now_playing (TMDB) ==========",
        "-- Generated by scripts/generate_movies_now_playing_seed.py",
        "-- Chi lu du lieu RAP: tmdb_id + duration + age_label (title/poster lay tu TMDB luc hien thi)",
        "-- Ket noi phong/ghe qua showtimes (movie_id), KHONG qua truc tiep movies -> seats",
        "",
    ]
    for row in enriched:
        note = f"now_playing: {row['title'][:180]}"
        lines.append(
            "INSERT IGNORE INTO movies "
            "(tmdb_id, duration, age_label, status, published_at, default_base_price, admin_note, runtime_synced_at) VALUES ("
            f"{row['tmdb_id']}, {row['runtime']}, {sql_escape(row['age_label'])}, 'ACTIVE', NOW(), "
            f"{DEFAULT_PRICE:.2f}, {sql_escape(note)}, NOW());"
        )
    lines.append(f"-- ({len(enriched)} rows)")
    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"\nWrote SQL: {OUT_SQL}")
    print(f"Wrote JSON: {OUT_JSON}")
    print(f"Total: {len(enriched)} movies")


if __name__ == "__main__":
    main()
